server:
  port: 8080

---

spring:
  profiles: default
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: order
          destination: mall
          contentType: application/json
        event-out:
          destination: mall
          contentType: application/json

logging:
  level:
    root: ${ORDER_LOG_LEVEL}
    org:
      hibernate:
        SQL: ${ORDER_LOG_LEVEL}
      springframework:
        cloud: ${ORDER_LOG_LEVEL}


server:
  port: 8081
---

spring:
  profiles: docker
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true  
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: order
          destination: mall
          contentType: application/json
        event-out:
          destination: mall
          contentType: application/json

logging:
  level:
    root: ${ORDER_LOG_LEVEL}
    org:
      hibernate:
        SQL: ${ORDER_LOG_LEVEL}
      springframework:
        cloud: ${ORDER_LOG_LEVEL}
